import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { fetchRepositories } from '../store/actions';
import { RootState } from '../types';
import { Box, Grid, SimpleGrid, Container, VStack, Center, Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer, } from "@chakra-ui/react"

const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const dispatch = useDispatch();
  const repositories = useSelector((state: RootState) => state.repositories);

  useEffect(() => {
    dispatch(fetchRepositories('herry-y238'));
  }, [dispatch]);
  return (
    <>
      <Head>
        <title>List of Public Repositories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack>
        <Container maxW='container.lg'>
          <Center h='100px' color='black'>
            <h2 className='title-main'>List of Public Repositories</h2>
          </Center>
        </Container>
      </VStack>

      <VStack>
        <Container maxW='container.lg'>
          <TableContainer>
            <Table variant='striped' colorScheme='blackAlpha'>
              <Thead>
                <Tr>
                  <Th>Title</Th>
                  <Th>URL</Th>
                  <Th>Description</Th>
                </Tr>
              </Thead>
              <Tbody>
                {repositories.map((repo) => (
                  <Tr key={repo.id}>
                    <Td>{repo.name}</Td>
                    <Td><a href={repo.html_url}>{repo.html_url}</a></Td>
                    <Td>{repo.description}</Td>
                  </Tr>
                ))}
              </Tbody>
            </Table>
          </TableContainer>
        </Container>
      </VStack>
    </>
  )
}
